/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#e2e2e3",
        "inverse-on-surface": "#313032",
        "secondary-container": "#4a4b53",
        "secondary": "#c6c5cf",
        "surface": "#131315",
        "surface-container": "#201f22",
        "on-surface-variant": "#c4c7c9",
        "secondary-fixed": "#e3e1ec",
        "surface-container-high": "#2a2a2c",
        "error": "#ffb4ab",
        "primary": "#ffffff",
        "on-tertiary-fixed-variant": "#005236",
        "on-secondary-fixed": "#1a1b22",
        "inverse-surface": "#e5e1e4",
        "tertiary-fixed": "#6ffbbe",
        "surface-container-highest": "#353437",
        "error-container": "#93000a",
        "surface-dim": "#131315",
        "on-background": "#e5e1e4",
        "on-tertiary-container": "#00734e",
        "on-secondary-fixed-variant": "#46464e",
        "tertiary-container": "#6ffbbe",
        "surface-tint": "#c6c6c7",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#c6c5cf",
        "on-secondary-container": "#bcbbc5",
        "tertiary-fixed-dim": "#4edea3",
        "surface-container-lowest": "#0e0e10",
        "on-primary-fixed-variant": "#454748",
        "surface-variant": "#353437",
        "background": "#131315",
        "on-secondary": "#2f3038",
        "surface-bright": "#39393b",
        "on-primary": "#2f3132",
        "outline": "#8e9193",
        "on-tertiary-fixed": "#002113",
        "surface-container-low": "#1c1b1d",
        "inverse-primary": "#5d5e60",
        "primary-container": "#e2e2e3",
        "primary-fixed-dim": "#c6c6c7",
        "on-primary-container": "#636466",
        "outline-variant": "#444749",
        "on-primary-fixed": "#1a1c1d",
        "on-surface": "#e5e1e4",
        "on-tertiary": "#003824",
        "tertiary": "#ffffff"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "space-lg": "1rem",
        "margin": "1.5rem",
        "space-2xs": "0.125rem",
        "space-2xl": "2rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-xl": "1.5rem",
        "gutter": "1rem",
        "margin-compact": "1rem",
        "gutter-dense": "0.5rem"
      },
      fontFamily: {
        sans: ["Geist", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "headline-sm": ["Geist", "sans-serif"],
        "label-default": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Geist", "sans-serif"],
        "display": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "body-default": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "kbd": ["JetBrains Mono", "monospace"],
        "body-lg": ["Geist", "sans-serif"]
      },
      fontSize: {
        "body-sm": "12px",
        "headline-lg": "24px",
        "display": "32px",
        "label-sm": "11px",
        "headline-md": "18px",
        "headline-sm": "15px",
        "body-default": "13px",
        "body-lg": "15px",
        "kbd": "10px",
        "label-default": "12px"
      },
      lineHeight: {
        "body-default": "20px",
        "label-default": "16px",
        "headline-sm": "22px",
        "headline-md": "26px",
        "display": "40px",
        "body-lg": "24px",
        "body-sm": "18px",
        "headline-lg": "32px",
        "kbd": "12px",
        "label-sm": "14px"
      },
      letterSpacing: {
        "label-sm": "0.04em",
        "body-lg": "-0.01em",
        "headline-sm": "-0.015em",
        "kbd": "0.05em",
        "body-default": "-0.005em",
        "headline-lg": "-0.025em",
        "headline-md": "-0.02em",
        "body-sm": "0em",
        "display": "-0.03em",
        "label-default": "0.02em"
      },
      fontWeight: {
        "body-default": "400",
        "display": "600",
        "body-sm": "400",
        "headline-md": "600",
        "headline-lg": "600",
        "body-lg": "400",
        "kbd": "500",
        "label-default": "500",
        "headline-sm": "500",
        "label-sm": "500"
      }
    }
  },
  plugins: [],
}
